name: MultiSensor
dependencies:
  - python=3.7.4
  - matplotlib
  - pip:
      - tensorflow==2.6.2
      - tensorflow-probability==0.14.1
      - gpflow==2.1.4
      - pandas==1.3.4
      - xlrd==1.2.0
      - openpyxl
      - protobuf==3.20.*
      - dill
      - jupyterlab
